import React from 'react';

export default [
    {
        group_name: 'Básicas',
        questions: [
            {question: 'Olá, como você está?'},
            {question: 'O que você gosta de fazer pra se divertir?'},
            {question: 'Qual o seu signo?'},
            {question: 'Qual sua comida favorita?'},
            {question: 'Qual a cor do seu cabelo?'},
            {question: 'Você pensa em pintar o cabelo? Se sim, qual cor?'},
            {question: 'Você já pensou em fazer tatuagem? Se sim, o que você faria?'},
            {question: 'Você pensa em fazer faculdade? Qual curso você gostaria de fazer?'},
            {question: 'Qual a materia que você mais gosta (ou gostava) na escola?'},
            {question: 'Quantos amigos você tem (ou tinha) na escola?'},
            {question: 'O que você acha do Enem?'},
            {question: 'Você gosta de desenhar?'},
            {question: 'Como você avaliaria a sua própria habilidade de desenhos?'},
            {question: 'Você gosta de história?'},
            {question: ' Qual série você mais gosta?'},
            {question: 'Você gosta de anime? Se sim, qual seu anime favorito?'},
            {question: 'Qual anime já fez você chorar?'},
            {question: 'Qual categoria de história você mais gosta?'},
            {question: 'Você ta apaixonado(a) por alguém? Se sim, essa pessoa sabe?'},
            {question: 'Você ta namorando?'},
            {question: 'Você tem um crush em algum personagem de anime? Se sim, qual?'},
            {question: 'Você gosta de Pizza? Qual seu sabor favorito?'},
            {question: 'O que você gosta de fazer no seu tempo livre?'},
            {question: 'Você gosta dos seus pais?'},
            {question: 'O que você pensa do presidente do seu país?'},
            {question: 'Você ta louco pra tomar a vacina?'},
            {question: 'Você abraçaria a pessoa que você mais ama?'},
            {question: 'Você perdoaria alguém que machucou alguém que você ama?'},
            {question: 'Você perdoaria alguém te que machucou?'},
            {question: 'O que você faz pra manter a forma?'},
            {question: 'Bolacha ou Biscoito?'},
            {question: 'Doce ou Salgado?'}
        ]
    },
    {
        group_name: 'Anime 01',
        questions: [
            {question: 'Você gosta de animes?'},
            {question: 'Qual seu anime favorito?'},
            {question: 'Qual o pior anime que você já viu?'},
            {question: 'Qual o pior anime que já te recomendaram?'},
            {question: 'Qual o melhor anime que já te recomendaram?'},
            {question: 'Algum anime já te ajudou a namorar alguém?'},
            {question: 'Algum anime já te fez ter uma briga com seu parceiro?'},
            {question: 'Algum anime já te fez brigar com algum amigo?'},
            {question: 'Qual o melhor anime de terror na sua opinião?'},
            {question: 'Qual o melhor anime de ação e aventura na sua opinião?'},
            {question: 'Qual o melhor anime de Slice of Life você já viu?'},
            {question: 'Qual o melhor filme do Studio Ghibli pra você?'},
            {question: 'Qual o personagem que você mais gosta?'},
            {question: 'Se você pudesse ir para algum mundo de anime, qual seria?'},
            {question: 'Que mundo de naime você NUNCA iria querer ir?'},
            {question: 'Que personagem de anime você iria querer dar um soco na cara?'},
            {question: 'Que personagem de anime você iria querer ser BFF?'},
            {question: 'Quando você viu seu primeiro anime?'},
            {question: 'Qual anime mais memorável pra você?'},
            {question: 'Que anime já te deu muita raiva?'},
            {question: 'Que anime já te deixou traumatizado?'},
            {question: 'Você gosta de Attack on Titan?'},
            {question: 'Você gosta de Boku no Hero?'},
            {question: 'Já viu One Piece?'},
            {question: 'Boku no Pico te deixou tão traumatizado quanto eu?'},
            {question: 'Quem você acha melhor? Luffy ou Naruto?'},
            {question: 'L ou Kira?'},
            {question: 'Animes 2d ou 3d?'},
            {question: 'Bolacha ou Biscoito?'},
            {question: 'Doce ou Salgado?'}
        ]
    },
    {
        group_name: 'Basics',
        questions: [
            {question: 'Hi, How are you?'},
            {question: 'What\'s up?'},
            {question: 'What do you like to do for fun?'},
            {question: 'What\'s your sign?'},
            {question: 'What\'s your favority food'},
            {question: 'What\'s the color or your hair?'},
            {question: 'Do you think about dye your hairr? If yes, what color?'},
            {question: 'Have you ever thought about getting a tattoo? If yes, what would you do?'},
            {question: 'Do you think about going to college? Which course would you like to do?'},
            {question: 'What subject do you like (or liked) the most in school?'},
            {question: 'How many friends do you have (or had) at school?'},
            {question: 'Do you like do draw?'},
            {question: 'How would you rate your own drawing ability?'},
            {question: 'You like history?'},
            {question: 'Which series do you like the most?'},
            {question: 'Do you like anime? If yes, what is your favorite anime?'},
            {question: 'Which anime ever made you cry?'},
            {question: 'Which story category do you like best?'},
            {question: 'Are you in love with someone? If yes, does this person know?'},
            {question: 'Are you dating?'},
            {question: 'Do you have a crush on any anime character? If yes, which one?'},
            {question: 'Do you like pizza? What is your favorite flavor?'},
            {question: 'What do you like to do in your spare time?'},
            {question: 'Do you like your parents?'},
            {question: 'Do you like your country?'},
            {question: 'What do you think of the president of your country?'},
            {question: 'Are you dying to get the vaccine?'},
            {question: 'Would you hug the person you love the most?'},
            {question: 'Would you forgive someone who hurt someone you love?'},
            {question: 'Would you forgive someone who hurt you?'},
            {question: 'What do you do to maintain body shape?'},
            {question: 'Sweet or Salty?'}
        ]
    },
    {
        group_name: 'Anime English 01',
        questions: [
            {question: 'Do you like animes?'},
            {question: 'What\'s your favority anime?'},
            {question: 'What\'s the worst anime you\'ve ever seen?'},
            {question: 'What\'s the worst anime you\'ve ever been recommended?'},
            {question: 'What\'s the best anime you\'ve ever been recommended?'},
            {question: 'Has any anime ever helped you to date someone?'},
            {question: 'Has any anime ever made you have a fight with your partner?'},
            {question: 'Has any anime ever made you fight with a friend?'},
            {question: 'What is the best horror anime in your opinion?'},
            {question: 'What is the best action-adventure anime in your opinion?'},
            {question: 'What\'s the best Slice of Life anime you\'ve seen?'},
            {question: 'What is the best Studio Ghibli movie for you?'},
            {question: 'Which character do you like the most?'},
            {question: 'If you could go to an anime world, which would it be?'},
            {question: 'What anime world would you NEVER want to go to?'},
            {question: 'What anime character would you want to punch in the face?'},
            {question: 'What anime character would you want to be BFF?'},
            {question: 'When did you see your first anime?'},
            {question: 'Which anime is the most memorable for you?'},
            {question: 'What anime has made you so angry?'},
            {question: 'What anime has left you traumatized?'},
            {question: 'Do you like Attack on Titan?'},
            {question: 'Do you like Boku no Hero?'},
            {question: 'Have you ever seen One Piece?'},
            {question: 'Boku no Pico left you as traumatized as I was?'},
            {question: 'Who do you think is better? Luffy or Naruto?'},
            {question: 'L or Kira?'},
            {question: 'Animes 2d or 3d?'}
        ]
    },
] as any;