import React from 'react';

export default [
    {
        nome_grupo: 'Básicas',
        perguntas: [
            {questao: 'Olá, como você está?'},
            {questao: 'O que você gosta de fazer pra se divertir?'},
            {questao: 'Qual o seu signo?'},
            {questao: 'Qual sua comida favorita?'},
            {questao: 'Qual a cor do seu cabelo?'},
            {questao: 'Você pensa em pintar o cabelo? Se sim, qual cor?'},
            {questao: 'Você já pensou em fazer tatuagem? Se sim, o que você faria?'},
            {questao: 'Você pensa em fazer faculdade? Qual curso você gostaria de fazer?'},
            {questao: 'Qual a materia que você mais gosta (ou gostava) na escola?'},
            {questao: 'Quantos amigos você tem (ou tinha) na escola?'},
            {questao: 'O que você acha do Enem?'},
            {questao: 'Você gosta de desenhar?'},
            {questao: 'Como você avaliaria a sua própria habilidade de desenhos?'},
            {questao: 'Você gosta de história?'},
            {questao: ' Qual série você mais gosta?'},
            {questao: 'Você gosta de anime? Se sim, qual seu anime favorito?'},
            {questao: 'Qual anime já fez você chorar?'},
            {questao: 'Qual categoria de história você mais gosta?'},
            {questao: 'Você ta apaixonado(a) por alguém? Se sim, essa pessoa sabe?'},
            {questao: 'Você ta namorando?'},
            {questao: 'Você tem um crush em algum personagem de anime? Se sim, qual?'},
            {questao: 'Você gosta de Pizza? Qual seu sabor favorito?'},
            {questao: 'O que você gosta de fazer no seu tempo livre?'},
            {questao: 'Você gosta dos seus pais?'},
            {questao: 'O que você pensa do presidente do seu país?'},
            {questao: 'Você ta louco pra tomar a vacina?'},
            {questao: 'Você abraçaria a pessoa que você mais ama?'},
            {questao: 'Você perdoaria alguém que machucou alguém que você ama?'},
            {questao: 'Você perdoaria alguém te que machucou?'},
            {questao: 'O que você faz pra manter a forma?'},
            {questao: 'Bolacha ou Biscoito?'},
            {questao: 'Doce ou Salgado?'}
        ]
    },
    {
        nome_grupo: 'Anime 01',
        perguntas: [
            {questao: 'Você gosta de animes?'},
            {questao: 'Qual seu anime favorito?'},
            {questao: 'Qual o pior anime que você já viu?'},
            {questao: 'Qual o pior anime que já te recomendaram?'},
            {questao: 'Qual o melhor anime que já te recomendaram?'},
            {questao: 'Algum anime já te ajudou a namorar alguém?'},
            {questao: 'Algum anime já te fez ter uma briga com seu parceiro?'},
            {questao: 'Algum anime já te fez brigar com algum amigo?'},
            {questao: 'Qual o melhor anime de terror na sua opinião?'},
            {questao: 'Qual o melhor anime de ação e aventura na sua opinião?'},
            {questao: 'Qual o melhor anime de Slice of Life você já viu?'},
            {questao: 'Qual o melhor filme do Studio Ghibli pra você?'},
            {questao: 'Qual o personagem que você mais gosta?'},
            {questao: 'Se você pudesse ir para algum mundo de anime, qual seria?'},
            {questao: 'Que mundo de naime você NUNCA iria querer ir?'},
            {questao: 'Que personagem de anime você iria querer dar um soco na cara?'},
            {questao: 'Que personagem de anime você iria querer ser BFF?'},
            {questao: 'Quando você viu seu primeiro anime?'},
            {questao: 'Qual anime mais memorável pra você?'},
            {questao: 'Que anime já te deu muita raiva?'},
            {questao: 'Que anime já te deixou traumatizado?'},
            {questao: 'Você gosta de Attack on Titan?'},
            {questao: 'Você gosta de Boku no Hero?'},
            {questao: 'Já viu One Piece?'},
            {questao: 'Boku no Pico te deixou tão traumatizado quanto eu?'},
            {questao: 'Quem você acha melhor? Luffy ou Naruto?'},
            {questao: 'L ou Kira?'},
            {questao: 'Animes 2d ou 3d?'},
            {questao: 'Bolacha ou Biscoito?'},
            {questao: 'Doce ou Salgado?'}
        ]
    }
] as any;